routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(["guest:admin"])->get('/', function () {
    return view('auth.login');
});

// Route::get('/', 'HomeController@inde')->name("test1");


Route::group(['middleware' => ['auth:admin']], function () {
    Route::get('/dashboard', 'HomeController@dashboard')->name("dashboard");
    Route::resource('companies', 'CompanyController');
    Route::post('companies/{company}/delete-logo', "CompanyController@deleteLogo")->name("companies.delete-logo");
    Route::resource('employees', 'EmployeeController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory;
    use SoftDeletes;

    // append extra custom attribute to model
    protected $fillable = array(
        'name',
        'logo_link',
        'email',
        'website',
    );

    public function employees() {
        return $this->hasMany(Employee::class, "company_id", "id");
    }

    public function getCompanyByEmail($email, $exceptCompanyId = 0) 
    {
        return $this->firstWhere([
            ['email', $email],
            ['id', '<>' , $exceptCompanyId],
        ]);
    }

    public function isExistingEmail($email, $exceptCompanyId = 0) 
    {
        if ($this->getCompanyByEmail($email, $exceptCompanyId)) {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use Log;
use Session;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Models\Company;
use App\Http\Requests\CreateCompanyRequest;
use App\Http\Requests\UpdateCompanyRequest;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::latest()->get();
        return view('admin.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCompanyRequest $request)
    {
        try {
            $company = Company::create([
                'name'  => $request->name,
                'email' => $request->email,
                'website'  => $request->website,
            ]);

            if ($request->hasFile('logo')) {
                $uploadPath = "assets/web/images/companies/$company->id/";
                $file      = $request->file('logo');
                $fileName = $request->logo->getClientOriginalName();
                $uploadSuccess = $file->move($uploadPath, $fileName); // uploading file to given path
                if (!$uploadSuccess) {
                    return redirect()->route("admin.companies.create")->with("failure", "Error when tried to save company logo.")->withInput();
                }

                $imageLink = $uploadPath . $fileName;
                $company->update([
                    'logo_link' => asset($imageLink),
                ]);
            };

            Session::flash('success', 'Company has been created successfully.');
            return redirect()->route('admin.companies.show', $company);
        } catch (\Exception $e) {
            Log::info($e);
            Session::flash('error', 'Error while tried to create company.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        return view('admin.companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        try {
            $company->update([
                'name' => $request->name,
                'email' => $request->email,
                'website' => $request->website,
            ]);

            if ($request->hasFile('logo')) {
                // delete logo
                $companyLogo = $company->logo_link;
                if ($companyLogo) {
                    $adminUrl = config('app.admin_url');
                    $path = str_replace($adminUrl, '', $companyLogo);
                    $file = public_path($path);

                    if (file_exists($file)) {
                        $deleteFile = unlink($file);
                        File::delete($file);

                        if (!$deleteFile) {
                            throw new Exception('Error while try to delete logo');
                        }

                        $company->update([
                            'logo_link' => null,
                        ]);
                    }
                }

                // upload logo
                $uploadPath = "assets/web/images/companies/$company->id/";
                $file      = $request->file('logo');
                $fileName = $request->logo->getClientOriginalName();
                $uploadSuccess = $file->move($uploadPath, $fileName); // uploading file to given path
                if (!$uploadSuccess) {
                    return redirect()->route("admin.companies.update")->with("failure", "Error when tried to save company logo.")->withInput();
                }

                $imageLink = $uploadPath . $fileName;
                $company->update([
                    'logo_link' => asset($imageLink),
                ]);
            };

            Session::flash('success', 'Company has been updated successfully.');
            return redirect()->route('admin.companies.show', $company);
        } catch (\Exception $e) {
            Log::info($e);
            Session::flash('error', 'Error while tried to update company. ('.$e->getMessage().')');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        if (!empty($company)) {

            // reset those employees under selected company
            if(count($company->employees) > 0) {
                foreach($company->employees as $employee) {
                    $employee->update([
                        'company_id' => null,
                    ]);
                }
            }

            $adminUrl = config('app.admin_url');

            if ($company->logo_link){
                $logoPath = str_replace($adminUrl, '', $company->logo_link);
                $profileImageFile = public_path($logoPath);

                if (file_exists($profileImageFile)) {
                    $profileImageDeleteFile = unlink($profileImageFile);
                    File::delete($company->logo_link);
                }

                $company->update([
                    'logo_link' => null,
                ]);
            }

            // delete company folder as well
            File::deleteDirectory(public_path('assets/web/images/companies/'. $company->id));

            $company->delete();

            Session::flash('success', 'Company has been deleted successfully.');
        }

        return redirect()->route('admin.companies.index');
    }

    public function deleteLogo(Company $company) {
        try{
            $companyLogo = $company->logo_link;
            if ($companyLogo) {
                $adminUrl = config('app.admin_url');
                $path = str_replace($adminUrl, '', $companyLogo);
                $file = public_path($path);

                if (file_exists($file)) {
                    $deleteFile = unlink($file);
                    File::delete($file);

                    if (!$deleteFile) {
                        return response()->json(['success' => false, 'message' => 'Error deleting file']);
                    }

                    $company->update([
                        'logo_link' => null,
                    ]);
                }
            }
            return response()->json(['success' => true, 'message' => null]);
        } catch (\Exception $e) {
            Log::info($e);
            Session::flash('error', 'Error deleting file. ('.$e->getMessage().')');
            return response()->json(['success' => false, 'message' => 'Error deleting file']);
        }
    }
}

resources/views/admin/companies/create.blade.php
@extends('admin.layouts.app')

@section("content")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create Company</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.companies.index') }}">Companies</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-12 text-right">
                        <div class="form-group">
                            <a class="btn btn-primary text-white" href="{{ route('admin.companies.index') }}"><i class="fa fa-list"></i> Index</a>
                        </div>
                    </div>
                    @include('admin.layouts.includes.notification')
                    <form action="{{ route('admin.companies.store') }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        <div class="card card-primary">
                            <div class="card-header bg-gray">
                                <b class="card-title"><i class="fas fa-building"></i> Company Information</b>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Name* :</label>
                                            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Enter name..." value="{{ old('name') }}" required>
                                            @error('name')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Email :</label>
                                            <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Enter email..." value="{{ old('email') }}">
                                            @error('email')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label for="logo">Logo :</label>
                                            <input type="file" accept="image/*" class="form-control @error('logo') is-invalid @enderror" name="logo" value="{{ old('logo') }}">
                                            <small>Recommend to upload <b>jpeg/jpg or png</b> image format; <br>size recommended to <b>minumum 100px x 100px</b></small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Website :</label>
                                            <input type="text" class="form-control @error('website') is-invalid @enderror" name="website" placeholder="Enter website..." value="{{ old('website') }}">
                                            @error('website')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success float-right"><i class="fa fa-plus"></i> Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/companies/index.blade.php
@extends('admin.layouts.app')
@section("content")


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Companies</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Companies</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-12 text-right">
                        <div class="form-group">
                            <a class="btn btn-success text-white" href="{{ route('admin.companies.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a>
                        </div>
                    </div>
                </div>
                @include('admin.layouts.includes.notification')
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table table-bordered table-hover" id="company-table">
                            <thead>
                                <tr class="table-success">
                                    <th>No</th>
                                    <th nowrap>Company Name</th>
                                    <th nowrap>Email</th>
                                    <th>Logo</th>
                                    <th>Website</th>
                                    <th nowrap>Created Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($companies ?? [] as $key => $company)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $company->name }}</td>
                                    <td>
                                        @if($company->email)
                                        <a href="mailto:{{$company->email}}">{{$company->email}}</a>                                            
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td>
                                        @if($company->logo_link != '')
                                        <img src="{{ asset($company->logo_link) }}" width="100" alt="Company Logo">
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td>
                                        @if($company->website)
                                        <a href="{{$company->website}}" target="_blank">{{$company->website}}</a>                                            
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td nowrap>{{ date_format(date_create($company->created_at), 'Y-m-d h:i A') }}</td>
                                    <td nowrap>
                                        <a class="btn btn-primary" href="{{ route('admin.companies.show', $company) }}"><i class="fa fa-eye"></i></a>
                                        <a class="btn btn-warning" href="{{ route('admin.companies.edit', $company) }}"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger delete-btn" data-href="#" data-type="company">
                                            <i class="fa fa-trash"></i>
                                            <form action="{{ route('admin.companies.destroy', $company) }}" method="POST" class="d-none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function () {
        // $('#company-table').DataTable({
        //     // "paging": true,
        //     // "lengthChange": false,
        //     // "searching": false,
        //     // "ordering": true,
        //     // "info": true,
        //     "autoWidth": true,
        //     // "responsive": true,
        // });
    })
</script>
@endsection

resources/views/admin/companies/show.blade.php
@extends('admin.layouts.app')
@section("content")

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Show Company</h1>
                    </div>
                    <div class="col-sm-6">          
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('admin.companies.index')}}">Companies</a></li>
                            <li class="breadcrumb-item active">Show</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-12 text-right">
                                <div class="form-group">
                                    <a class="btn btn-primary text-white" href="{{ route('admin.companies.index') }}"><i class="fa fa-list" aria-hidden="true"></i> Index</a>
                                    <a class="btn btn-warning text-white" href="{{ route('admin.companies.edit', $company) }}"><i class="fa fa-edit" aria-hidden="true"></i> Edit</a>
                                    <a class="btn btn-danger text-white delete-btn" data-type="company">
                                        <i class="fa fa-trash" aria-hidden="true"></i> 
                                        <form action="{{ route('admin.companies.destroy', $company) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                        @include('admin.layouts.includes.notification')
                        <div class="card card-primary">
                            <div class="card-header bg-gray">
                                <b class="card-title"><i class="fas fa-building"></i> Company Information</b>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Company Name :</label>
                                            <p class="form-control-static">{{ $company->name ?? '-' }}</p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Email :</label>
                                            <p class="form-control-static">
                                                @if($company->email)
                                                <a href="mailto:{{$company->email}}">{{$company->email}}</a>                                            
                                                @else
                                                -
                                                @endif    
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Logo :</label>
                                            <p class="form-control-static">
                                                @if($company->logo_link)
                                                <img src="{{ asset($company->logo_link) }}" width="80%" alt="Company Logo">
                                                @else
                                                -
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Website :</label>
                                            <p class="form-control-static">
                                                @if($company->website)
                                                <a href="{{$company->website}}" target="_blank">{{$company->website}}</a>                                            
                                                @else
                                                -
                                                @endif    
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection