routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(["guest:admin"])->get('/', function () {
    return view('auth.login');
});

// Route::get('/', 'HomeController@inde')->name("test1");


Route::group(['middleware' => ['auth:admin']], function () {
    Route::get('/dashboard', 'HomeController@dashboard')->name("dashboard");
    Route::resource('companies', 'CompanyController');
    Route::post('companies/{company}/delete-logo', "CompanyController@deleteLogo")->name("companies.delete-logo");
    Route::resource('employees', 'EmployeeController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Company;

class Employee extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = array(
        'first_name',
        'last_name',
        'company_id',
        'email',
        'mobile_no',
    );

    public function company() {
        return $this->belongsTo(Company::class);
    }

    public function getFullNameAttribute(){
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getEmployeeByEmail($email, $exceptEmployeeId = 0) 
    {
        return $this->firstWhere([
            ['email', $email],
            ['id', '<>' , $exceptEmployeeId],
        ]);
    }

    public function isExistingEmail($email, $exceptEmployeeId = 0) 
    {
        if ($this->getEmployeeByEmail($email, $exceptEmployeeId)) {
            return true;
        }
        return false;
    }

    public function getEmployeeByMobileNo($mobileNo, $exceptEmployeeId = 0) 
    {
        return $this->firstWhere([
            ['mobile_no', $mobileNo],
            ['id', '<>' , $exceptEmployeeId],
        ]);
    }

    public function isExistingMobileNo($mobileNo, $exceptEmployeeId = 0) 
    {
        if ($this->getEmployeeByMobileNo($mobileNo, $exceptEmployeeId)) {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use Log;
use Session;
use Exception;
use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\Company;
use App\Http\Requests\CreateEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::latest()->get();
        return view('admin.employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::orderBy('name')->get();
        return view('admin.employees.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmployeeRequest $request)
    {
        try {
            $employee = Employee::create([
                'first_name'  => $request->first_name,
                'last_name'  => $request->last_name,
                'company_id' => $request->company,
                'email' => $request->email,
                'mobile_no'  => $request->mobile_no,
            ]);

            Session::flash('success', 'Employee has been created successfully.');
            return redirect()->route('admin.employees.show', $employee);
        } catch (\Exception $e) {
            Log::info($e);
            Session::flash('error', 'Error while tried to create employee.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('admin.employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $companies = Company::orderBy('name')->get();
        return view('admin.employees.edit', compact('employee', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        try {
            $employee->update([
                'first_name'  => $request->first_name,
                'last_name'  => $request->last_name,
                'company_id' => $request->company,
                'email' => $request->email,
                'mobile_no'  => $request->mobile_no,
            ]);

            Session::flash('success', 'Employee has been updated successfully.');
            return redirect()->route('admin.employees.show', $employee);
        } catch (\Exception $e) {
            Log::info($e);
            Session::flash('error', 'Error while tried to update employee.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        if (!empty($employee)) {
            $employee->delete();
            Session::flash('success', 'Employee has been deleted successfully.');
        }

        return redirect()->route('admin.employees.index');
    }
}

resources/views/admin/employees/create.blade.php
@extends('admin.layouts.app')

@section("content")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create Employee</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.employees.index') }}">Employees</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-12 text-right">
                        <div class="form-group">
                            <a class="btn btn-primary text-white" href="{{ route('admin.employees.index') }}"><i class="fa fa-list"></i> Index</a>
                        </div>
                    </div>
                    @include('admin.layouts.includes.notification')
                    <form action="{{ route('admin.employees.store') }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        <div class="card card-primary">
                            <div class="card-header bg-gray">
                                <b class="card-title"><i class="fas fa-users"></i> Employee Information</b>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">First Name* :</label>
                                            <input type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" placeholder="Enter first name..." value="{{ old('first_name') }}" required>
                                            @error('first_name')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Last Name* :</label>
                                            <input type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" placeholder="Enter last name..." value="{{ old('last_name') }}" required>
                                            @error('last_name')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Company :</label>
                                            <select name="company" class="form-control @error('company') is-invalid @enderror">
                                                <option value>Select company</option>
                                                @foreach ($companies as $company)
                                                    <option value="{{ $company['id'] }}" {{ $company['id'] == old('company') ? 'selected' : '' }}>{{ $company['name'] }}</option>
                                                @endforeach
                                            </select>
                                            @error('company')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Email :</label>
                                            <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Enter email..." value="{{ old('email') }}">
                                            @error('email')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Mobile No :</label>
                                            <input type="text" class="form-control @error('mobile_no') is-invalid @enderror" name="mobile_no" placeholder="Enter mobile no..." value="{{ old('mobile_no') }}">
                                            @error('mobile_no')
                                            <span class="invalid-feedback d-block" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success float-right"><i class="fa fa-plus"></i> Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('admin.layouts.app')
@section("content")


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Employees</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Employees</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-12 text-right">
                        <div class="form-group">
                            <a class="btn btn-success text-white" href="{{ route('admin.employees.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a>
                        </div>
                    </div>
                </div>
                @include('admin.layouts.includes.notification')
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table table-bordered table-hover" id="company-table">
                            <thead>
                                <tr class="table-success">
                                    <th>No</th>
                                    <th nowrap>Full Name</th>
                                    <th>Company</th>
                                    <th nowrap>Email</th>
                                    <th>Mobile No</th>
                                    <th nowrap>Created Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($employees ?? [] as $key => $employee)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $employee->full_name }}</td>
                                    <td>
                                        @if($employee->company)
                                        <a href="{{ route('admin.companies.show', $employee->company) }}">{{ $employee->company->name }}</a>
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td nowrap>
                                        @if($employee->email)
                                        <a href="mailto:{{$employee->email}}">{{$employee->email}}</a>                                            
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td>
                                        @if($employee->mobile_no)
                                        <a href="tel:{{$employee->mobile_no}}">{{$employee->mobile_no}}</a>                                            
                                        @else
                                        -
                                        @endif
                                    </td>
                                    <td nowrap>{{ date_format(date_create($employee->created_at), 'Y-m-d h:i A') }}</td>
                                    <td nowrap>
                                        <a class="btn btn-primary" href="{{ route('admin.employees.show', $employee) }}"><i class="fa fa-eye"></i></a>
                                        <a class="btn btn-warning" href="{{ route('admin.employees.edit', $employee) }}"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger delete-btn" data-href="#">
                                            <i class="fa fa-trash"></i>
                                            <form action="{{ route('admin.employees.destroy', $employee) }}" method="POST" class="d-none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function () {
        $('#company-table').DataTable({
            // "paging": true,
            // "lengthChange": false,
            // "searching": false,
            // "ordering": true,
            // "info": true,
            "autoWidth": true,
            // "responsive": true,
        });
    })
</script>
@endsection

resources/views/admin/employees/show.blade.php
@extends('admin.layouts.app')
@section("content")

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Show Employee</h1>
                    </div>
                    <div class="col-sm-6">          
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('admin.employees.index')}}">Employees</a></li>
                            <li class="breadcrumb-item active">Show</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-12 text-right">
                                <div class="form-group">
                                    <a class="btn btn-primary text-white" href="{{ route('admin.employees.index') }}"><i class="fa fa-list" aria-hidden="true"></i> Index</a>
                                    <a class="btn btn-warning text-white" href="{{ route('admin.employees.edit', $employee) }}"><i class="fa fa-edit" aria-hidden="true"></i> Edit</a>
                                    <a class="btn btn-danger text-white delete-btn">
                                        <i class="fa fa-trash" aria-hidden="true"></i> 
                                        <form action="{{ route('admin.employees.destroy', $employee) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                        @include('admin.layouts.includes.notification')
                        <div class="card card-primary">
                            <div class="card-header bg-gray">
                                <b class="card-title"><i class="fas fa-users"></i> Employee Information</b>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">First Name :</label>
                                            <p class="form-control-static">{{ $employee->first_name ?? '-' }}</p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Last Name :</label>
                                            <p class="form-control-static">{{ $employee->last_name ?? '-' }}</p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Company :</label>
                                            <p class="form-control-static">
                                                @if($employee->company)
                                                <a href="{{ route('admin.companies.show', $employee->company) }}">{{ $employee->company->name }}</a>
                                                @else
                                                -
                                                @endif    
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Email :</label>
                                            <p class="form-control-static">
                                                @if($employee->email)
                                                <a href="mailto:{{$employee->email}}">{{$employee->email}}</a>                                            
                                                @else
                                                -
                                                @endif    
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 mt-1">
                                        <div class="form-group">
                                            <label class="control-label">Mobile No :</label>
                                            <p class="form-control-static">
                                                @if($employee->mobile_no)
                                                <a href="tel:{{$employee->mobile_no}}">{{$employee->mobile_no}}</a>                                            
                                                @else
                                                -
                                                @endif    
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection